export const EXTERNAL_CONNECTED = "EXTERNAL_CONNECTED";
export const EXTERNAL_CLOSED = "EXTERNAL_CLOSED";
export const EXTERNAL_TERMINATED = "EXTERNAL_TERMINATED";
export const EXTERNAL_RECEIVED = "EXTERNAL_RECEIVED";
export const EXTERNAL_ERROR = "EXTERNAL_ERROR";
export const EXTERNAL_SENT = "EXTERNAL_SENT";

